config/routes.rb
Rails.application.routes.draw do

  #devise_for :users
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  resource :user

  #get 'sites/index'
  #root to: "sites#index"
  get 'statics/top'
  get 'statics/first'
  get 'statics/functions'
  root to: 'statics#top'

  resources :teams do
    member do
      post 'delegate'
    end
    resources :assigns, only: %w(create destroy)
    resources :sites do
      collection do
        post :confirm
      end
      member do
        post :confirm_edit
      end
      resources :comments, shallow: true
      resources :image_posts, shallow: true
      get 'search'
    end
  end

  resources :labels

#  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true, length: {maximum: 4096}

  belongs_to :user
  belongs_to :site
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :check_guest_user, only: [:create, :update, :destroy]
  before_action :set_comment, only: [:edit, :update, :destroy]

  def create
    @site = Site.find(params[:site_id])
    @comment = @site.comments.build(comment_params)
    @comment.user_id = current_user.id

    respond_to do |format|
      if @comment.save
        flash.now[:notice] = I18n.t('views.messages.post_comment')
        format.js { render :index }
      else
        flash.now[:alert] = I18n.t('views.messages.failed_to_post_comment')
        format.js { render :new_error }
      end
    end
  end

  def edit
    @comment = Comment.find(params[:id])
    @site = @comment.site

    respond_to do |format|
      flash.now[:notice] = I18n.t('views.messages.editing_comment')
      format.js { render :edit }
    end
  end

  def update
    @comment = Comment.find(params[:id])
    @site = @comment.site
      respond_to do |format|
        if @comment.update(comment_params)
          flash.now[:notice] = I18n.t('views.messages.update_comment')
          format.js { render :index }
        else
          flash.now[:alert] = I18n.t('views.messages.failed_to_update_comment')
          format.js { render :edit_error }
        end
      end
  end

  def destroy
    _site_id = @comment.site_id
    _team_id = @comment.site.team_id
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to team_site_path(_team_id, _site_id, anchor: "comments"), notice: I18n.t('views.messages.delete_comment') }
      format.json { head :no_content }
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:site_id, :content)
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end 
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_edit.html.erb
<%= form_with(model: [site, comment], url: comment_path(comment.id) ) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
      <ul>
        <% comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field(:content, id: "comment_content_#{site.id}", size: "32") %>
    <%= form.submit value: I18n.t('views.labels.edit_comment'), class: "btn btn-sm btn-info", id: "comment_submit_#{site.id}" %>
  </div>
<% end %>

app/views/comments/_edit_error.html.erb
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h5><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h5>
      <ul>
        <% comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

app/views/comments/_form.html.erb
<div class="col-auto">

  <%= form_with(model: [site, comment], url: team_site_comments_path(team_id: site.team.id, site_id: site.id)) do |form| %>
    <% if comment.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
        <ul>
        <% comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.text_field(:content, placeholder: I18n.t('views.messages.input_comment'), size: "32") %>
      <%= form.submit value: I18n.t('views.labels.add_comment'), class: "btn btn-sm btn-success" %> 
    </div>  
  <% end %>

</div> 

app/views/comments/_index.html.erb
<div class="row">
  <% comments.each do |comment| %>
    <% if comment.id.present? %>
	  <div class="col-auto">
	  	<div class="site_show_comment_item p-1 m-1 border rounded bg-light">
		  <%= raw Rinku.auto_link(simple_format(comment.content)) %>

		  <div>
	 	    <p class="site_comments_menu_links">[added by <%= comment.user.name %> at <%= l comment.updated_at, format: :short %> ]</p>	

			<div id="notice_comment_<%= comment.id %>"></div>

			<% if(current_user.keep_team.owner_id == current_user.id || comment.user_id == current_user.id) %>
			  <div class="site_comments_menu_links" id ="this_comment_<%= comment.id %>">
			    <%= link_to I18n.t('views.labels.comment_edit'), edit_comment_path(comment.id), class: "btn-sm btn-info", remote: true %>
			  </div>
			  <div class="site_comments_menu_links">
			    <%= link_to I18n.t('views.labels.comment_delete'), comment_path(comment.id), method: :delete, class: "btn-sm btn-danger", data: { confirm: I18n.t('views.messages.really_want_to_delete') } %>
			  </div>
			<% end %>
		  </div>
	  	
		</div>
	  </div>
    <% end %>  
  <% end %>
</div>

app/views/comments/edit.js.erb
$("#this_comment_<%= @comment.id %>").replaceWith("<%= j render 'comments/edit', site: @site, comment: @comment %>");
$("#notice").html("<div class='alert alert-info'><%= j flash[:notice] %></div>");

app/views/comments/edit_error.js.erb
$("#notice_comment_<%= @comment.id %>").replaceWith("<%= j render 'comments/edit_error', comment: @comment %>");
$("#notice").html("<div class='alert alert-danger'><%= j flash[:alert] %></div>");

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'comments/index', { comments: @comment.site.comments, site: @comment.site }) %>");
$("#comment_content").val('');
$("#notice").html("<div class='alert alert-info'><%= j flash[:notice] %></div>");

app/views/comments/new_error.js.erb
$("#notice").html("<div class='alert alert-danger'><%= j flash[:alert] %></div>");