config/routes.rb
Rails.application.routes.draw do

  #devise_for :users
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  resource :user

  #get 'sites/index'
  #root to: "sites#index"
  get 'statics/top'
  get 'statics/first'
  get 'statics/functions'
  root to: 'statics#top'

  resources :teams do
    member do
      post 'delegate'
    end
    resources :assigns, only: %w(create destroy)
    resources :sites do
      collection do
        post :confirm
      end
      member do
        post :confirm_edit
      end
      resources :comments, shallow: true
      resources :image_posts, shallow: true
      get 'search'
    end
  end

  resources :labels

#  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
end

app/views/shared/layout/_menu.html.erb
<!-- ナビゲーションバー start -->
<div class="smr_nav">
<nav class="navbar fixed-top navbar-expand-md navbar-dark bg-dark">      
  <%= link_to I18n.t('views.labels.link_menu_app_name'), root_path, class: "navbar-brand nav-link" %>  
  <button class="navbar-toggler" type="button"
          data-toggle="collapse"
          data-target="#navmenu1"
          aria-controls="navmenu1"
          aria-expanded="false"
          aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navmenu1">
    <div class="navbar-nav">


      <div class="dropdown">
        <a class="nav-item nav-link dropdown-toggle" data-toggle="dropdown" id="link_myteam_dropdown"><%= I18n.t('views.labels.link_menu_my_team') %></a>
        <div class="dropdown-menu">
          <% (current_user.teams.blank? ? Team.where(id: 1): current_user.teams.order(id: :asc)).each do |team| %>
	    
            <% if current_user.keep_team_id == team.id %>
            <div class="dropdown-item">
              <span class="fa-div"><i class="fas fa-check-square"></i></span>
              <%= link_to team.name, team_path(team.id) %>	      
            </div>
            <% else %>
            <div class="dropdown-item">
              <span class="fa-div"><i class="far fa-square"></i></span>
                    <%= link_to team.name, team_path(team.id) %>	      
            </div>
            <% end %>
          <% end %>

      	  <%= link_to I18n.t('views.labels.link_menu_new_team'), new_team_path, class: "dropdown-item" %>	  	    
        </div>
      </div>

      <%= link_to I18n.t('views.labels.link_menu_mypage'), user_path, class: "nav-item nav-link" %>
      <%= link_to I18n.t('views.labels.link_menu_site_index'), team_sites_path(1), class: "nav-item nav-link", id: "link_site_index_navitem" %>
      <% if current_user.id == current_user.keep_team.owner.id %>
        <%= link_to I18n.t('views.labels.link_menu_manage_label'), labels_path, class: "nav-item nav-link" %>
      <% end %>
      <%= link_to I18n.t('views.labels.link_menu_logout'), destroy_user_session_path, method: :delete, class: "nav-item nav-link", id: "link_menu_logout" %>
    </div>
  </div>
</nav>
</div>
<!-- ナビゲーションバー end -->

app/views/shared/layout/_menu2.html.erb
<!-- ナビゲーションバー start -->
<div class="smr_nav">
<nav class="navbar fixed-top navbar-expand-md navbar-dark bg-dark">      
  <%= link_to I18n.t('views.labels.link_menu_app_name'), root_path, class: "navbar-brand nav-link" %>  
  <button class="navbar-toggler" type="button"
          data-toggle="collapse"
          data-target="#navmenu1"
          aria-controls="navmenu1"
          aria-expanded="false"
          aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navmenu1">
    <div class="navbar-nav">
      <%= link_to I18n.t('views.labels.link_menu_site_index'), team_sites_path(1), class: "nav-item nav-link", id: "link_site_index_navitem" %>
      <%= link_to I18n.t('views.labels.link_menu_signup'), new_user_registration_path, class: "nav-item nav-link", id: "link_menu_signup" %>
      <%= link_to I18n.t('views.labels.link_menu_login'), new_user_session_path, class: "nav-item nav-link", id: "link_menu_login" %>
    </div>
  </div>
</nav>
</div>
<!-- ナビゲーションバー end -->