config/routes.rb
Rails.application.routes.draw do

  #devise_for :users
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  resource :user

  #get 'sites/index'
  #root to: "sites#index"
  get 'statics/top'
  get 'statics/first'
  get 'statics/functions'
  root to: 'statics#top'

  resources :teams do
    member do
      post 'delegate'
    end
    resources :assigns, only: %w(create destroy)
    resources :sites do
      collection do
        post :confirm
      end
      member do
        post :confirm_edit
      end
      resources :comments, shallow: true
      resources :image_posts, shallow: true
      get 'search'
    end
  end

  resources :labels

#  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  def top
  end

  def beginner
  end

  def functions
  end
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/views/statics/_link.html.erb
<%= link_to I18n.t('views.labels.link_back_to_statics_top'), statics_top_path %>

app/views/statics/first.html.erb
<article class="container_article">
<h1><%= I18n.t('views.labels.statics_first_title') %></h1>

<div class="card m-3" style="width:45rem;">
  <div class="card-header"><span class="font-weight-bold"><i class="fas fa-info-circle fa-lg"></i>&nbsp;&nbsp;初期状態</span></div>
  <div class="card-body">
    本アプリの利用者は、初回のログイン時には「DefaultTeam」というチームに属します。<BR>
    サイト情報（サンプル）：公衆トイレ一覧（渋谷区オープンデータ<BR>
    https://www.city.shibuya.tokyo.jp/kusei/tokei/opendata/index1.html）を加工して作成
  </div>
</div>

<div class="card m-3" style="width:45rem;">
  <div class="card-header"><span class="font-weight-bold"><i class="fas fa-info-circle fa-lg"></i>&nbsp;&nbsp;あたらしくチームを作成する<span></div>
  <div class="card-body">
    「マイページ」メニューから自分の所属するチームを確認できます。チームリーダの方は、<BR>
    「マイチーム」メニューからまずチームを作成し、メンバーを招待しましょう。<BR>
    チーム作成後は「ラベル管理」メニューからサイト情報に付与可能なラベル<BR>
    を作ることができます。ラベルの管理はチームリーダのみ可能です。
  </div>
</div>

<div class="card m-3" style="width:45rem;">
  <div class="card-header"><span class="font-weight-bold"><i class="fas fa-info-circle fa-lg"></i>&nbsp;&nbsp;自分のチームを確認したら</span></div>
  <div class="card-body">
    チームリーダからチームへの招待をうけた方には、システムからの通知メールが届きます。<BR>
    確認の上、「マイチーム」メニューから自分が招待されたチームを選択してください。<BR>
    選択後、「サイト情報」メニューから該当チームのサイト情報の閲覧・作業が可能と<BR>
    なります。
  </div>
</div>

<%= render 'link' %>
</article>

app/views/statics/functions.html.erb
<article class="container_article">
<h1><%= I18n.t('views.labels.statics_functions_title') %></h1>

<div class="card m-3" style="width:40rem;">
  <div class="card-header"><span class="font-weight-bold"><i class="fa fa-truck fa-lg" aria-hidden="true"></i>&nbsp;&nbsp;サイト情報の登録</span></div>
    <div class="card-body">
      利用者は、自分の所属するチーム内に納品先や取引先などのサイト情報を登録し、<BR>
      必要に応じて画像ファイルやURLリンク（現調報告書やGoogleマイマップなどを<BR>
      想定）を紐付けることで、チーム内でサイト情報を管理・共有することができます。
    </div>
  </div>
</div>

<div class="card m-3" style="width:40rem;">
  <div class="card-header"><span class="font-weight-bold"><i class="fa fa-truck fa-lg" aria-hidden="true"></i>&nbsp;&nbsp;サイト情報へのコメント・画像追加</span></div>
    <div class="card-body">
      サイト情報には、チームメンバー全員がコメント形式での気づきや現場の写真を<BR>
      追加できます。このことにより勘や経験に基づくさまざまな非定型情報の蓄積を<BR>
      図ることが可能です。
    </div>
  </div>
</div>

<div class="card m-3" style="width:40rem;">
  <div class="card-header"><span class="font-weight-bold"><i class="fa fa-truck fa-lg" aria-hidden="true"></i>&nbsp;&nbsp;ハッシュタグとラベル</span></div>
    <div class="card-body">
      サイト情報に対し、経由地などを表現するためのハッシュタグ、さらに用途など<BR>
      を表現するためのラベルを付加することで、関連するサイトを絞り込み検索により<BR>
      参照することが可能です。
    </div>
  </div>
</div>

<div class="card m-3" style="width:40rem;">
  <div class="card-header"><span class="font-weight-bold"><i class="fa fa-truck fa-lg" aria-hidden="true"></i>&nbsp;&nbsp;共有範囲（チーム）の作成</span></div>
    <div class="card-body">
      システムにログインした利用者は、自分のチームを新規に作成し、アカウント<BR>
      を持つメンバーをチームに招待することができます。本ツールでは、作成した<BR>
      チームが登録するサイト情報の共有範囲となります。
    </div>
  </div>
</div>

<div class="card m-3" style="width:40rem;">
  <div class="card-header"><span class="font-weight-bold"><i class="fa fa-truck fa-lg" aria-hidden="true"></i>&nbsp;&nbsp;Google KMLファイルの情報活用</span></div>
    <div class="card-body">
      サイト作成時には、<a href="https://www.google.co.jp/intl/ja/maps/about/mymaps/" target="_blank">Googleマイマップ</a>などから生成可能なKMLファイルの活用が<BR>
      可能です。新規作成画面からKMLファイルを読み込むと、プレイスマーク<BR>
      (Placemark)の名称(name)を本ツールのハッシュタグ、説明（description）を<BR>
      コメントとして取り込み、絞込み検索をおこなうことが可能となります。<BR>
      さらに、地点（Point）の緯度経度（coordinates）と説明(description)がマップ上に<BR>
      バルーンとして表示されます。 </div>
  </div>
</div>

<%= render 'link' %>
</article>

app/views/statics/top.html.erb
<article class="container_article">
<h1><%= I18n.t('views.top.welcome') %></h1>
<p>
  <%= I18n.t('views.top.line1') %><br>
  <%= I18n.t('views.top.line2') %><br>
  <%= I18n.t('views.top.line3') %><br>
</p>

<% if user_signed_in? %>
  <p><%= link_to I18n.t('views.messages.team_build2'), new_team_path %></p>
<% end %>

<%#= image_tag 'truck.jpg', width: "50%" %>


<div class="card-deck" style="width:56rem">
  <div class="card bg-light" style="width:24rem;">
    <%= image_tag '462525.png', class: "card-img-top", alt: "Card image cap" %>
    <div class="card-body">
      <h3 class="card-title font-weight-bold">はじめてご利用になる方へ</h3>
      <h6 class="card-subtitle text-monospace">・初期状態</h6>
      <p class="card-text">
        初回のログイン時には「DefaultTeam」というチームに属します。<BR>
        サイト情報（サンプル）：公衆トイレ一覧（渋谷区オープンデータ)
      <%= link_to raw("...&nbsp;<i class=\"fa fa-chevron-circle-right\" aria-hidden=\"true\"></i>"), statics_first_path, class: "card-link" %>
      </p>
     </div>
  </div>

  <div class="card bg-light" style="width:24rem;">
    <%= image_tag 'truck.jpg', class: "card-img-top", alt: "Card image cap" %>
    <div class="card-body">
      <h3 class="card-title font-weight-bold">できること</h3>
      <h6 class="card-subtitle">・サイト情報の登録</h6>
      <p class="card-text">利用者は、自分の所属するチーム内に納品先や取引先などのサイト情報を登録し、
      <%= link_to raw("...&nbsp;<i class=\"fa fa-chevron-circle-right\" aria-hidden=\"true\"></i>"), statics_functions_path, class: "card-link" %>
      </p>
    </div>
  </div>
</div>

</div>

</article>