config/routes.rb
Rails.application.routes.draw do

  #devise_for :users
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  resource :user

  #get 'sites/index'
  #root to: "sites#index"
  get 'statics/top'
  get 'statics/first'
  get 'statics/functions'
  root to: 'statics#top'

  resources :teams do
    member do
      post 'delegate'
    end
    resources :assigns, only: %w(create destroy)
    resources :sites do
      collection do
        post :confirm
      end
      member do
        post :confirm_edit
      end
      resources :comments, shallow: true
      resources :image_posts, shallow: true
      get 'search'
    end
  end

  resources :labels

#  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
end

app/models/site.rb
class Site < ApplicationRecord
  acts_as_taggable

  validates :name, presence: true, length: {maximum: 128}
  validates :address, length: {maximum: 255}
  validates :memo, length: {maximum: 255}

  has_many :comments, dependent: :destroy
  has_many :image_posts, dependent: :destroy
  belongs_to :user
  belongs_to :team

  has_many :site_labellings, dependent: :destroy, foreign_key: 'site_id'
  has_many :labels, through: :site_labellings, source: :label

  mount_uploader :kml, ImageUploader
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  before_action  :check_guest_user, only: [:new, :edit, :destroy]
  before_action  :set_site, only: [:show, :edit, :update, :destroy]

  def index    
    #check_specified_team
    @sites = current_user.keep_team.sites.includes([:site_labellings, :taggings, :user])

    if params[:q]
      @q = current_user.keep_team.sites.includes([:site_labellings, :taggings, :user]).ransack(search_params)
      @q.combinator = "or" if(params["and_or"]=="1")
      @sites = @q.result distinct: true
    else
      @q = Site.ransack(nil)
    end

    @sites = @sites.order(updated_at: :DESC).page(params[:page]).per(20)
  end

  def new
    @site = current_user.sites.build(team_id: current_user.keep_team_id)
  end

  def confirm    
    @site = Site.new(site_params)
    if site_params["kml"].present?
      if !(load_kml(site_params["kml"].path) )  
        @site.kml=nil
        params["site"]["kml"]=nil
      end 
    end

    @site.name = @document_name unless @site.name.present?
    @site.memo = @document_description unless @site.memo.present?
  end

  def create
    @site = current_user.sites.build(site_params)
    @site.team_id ||= current_user.keep_team_id

    if params[:back]
      render :new
    else
      if @site.save
        flash[:notice]=I18n.t('views.messages.create_site')
        redirect_to team_sites_path
      else
        flash.now[:alert]=I18n.t('views.messages.failed_create_site')
        render :new
      end
    end
  end

  def edit
    if !(site_creator_or_team_owner?)
      flash[:alert]=I18n.t('views.messages.unauthorized_request')
      redirect_to statics_top_path
    end
  end

  def confirm_edit
    @site=Site.new(site_params)   
    if (stored_site = Site.find(params[:id]))
      @site.comments = stored_site.comments
      @site.kml = stored_site.kml unless @site.kml.url
    end

    if site_params["kml"].present?
      if !(load_kml(site_params["kml"].path) )  
        @site.kml=nil
        params["site"]["kml"]=nil
      end 
    end 
    @site.name = @document_name if @document_name.present?
    @site.memo = @document_description if @document_description.present?
      
    render "confirm"
  end

  def update
    if params[:back]
      render :edit
    else
      if @site.update(site_params)
        flash[:notice]=I18n.t('views.messages.update_site')
        redirect_to team_sites_path
      else
        flash.now[:alert]=I18n.t('views.messages.failed_update_site')
        render :edit
      end
    end
  end

  def destroy
    if !(site_creator_or_team_owner?)
      flash[:alert]=I18n.t('views.messages.unauthorized_request')
      redirect_to statics_top_path
    end

    site_name=@site.name
    emails = @site.team.members.pluck(:email)
    emails << @site.team.owner.email

    if @site.destroy
      SiteMailer.destroy_mail(emails, site_name).deliver
      flash[:notice]=I18n.t('views.messages.delete_site')
      redirect_to team_sites_path
    else
      flash[:alert]=I18n.t('views.messages.failed_to_delete_site')
      redirect_to team_sites_path
    end
  end

  def show
    check_specified_team

    @comments = @site.comments.includes([:user])
    @comment = @site.comments.build
    @image_posts = @site.image_posts

    if(@site.kml.url)
      require "open-uri"
      require "rexml/document"
      #require "json/pure"     
      io = OpenURI.open_uri(@site.kml.url)
      kml = REXML::Document.new(io.read)
      elems_placemark = REXML::XPath.match(kml, '//Placemark')

=begin
      _points << ["<h1>東京</h1><p>人が多い</p>", 35.681391, 139.766103]
      _points << ["大阪", 34.702398, 135.495188]
      _points << ["札幌", 43.068612, 141.350768]
      @points = _points.to_json
=end
      
      _points = []; _line_strings = [] ; _polygons=[]
      elems_placemark.each do |elem|
        elem_ha = Hash.from_xml(elem.to_s)
        ha = elem_ha["Placemark"]
        if ha["Point"]
          coordinates = 
            ha["Point"]["coordinates"].split(/[,|\n|\t]/).map do |s|
              s.present? ? s.to_f : nil
            end.compact
          coordinates.unshift("<h5><strong>\##{ha["name"]}</strong></h5><span>#{ha["description"]}</span>")
          coordinates.unshift("\##{ha["name"]}")
          _points << coordinates
        elsif ha["LineString"]
          coordinates = 
            ha["LineString"]["coordinates"].split(/[,|\n|\t]/).map do |s|  
              s.present? ? s.to_f : nil
            end.compact
          coordinates.unshift("<h5><strong>\##{ha["name"]}</strong></h5><span>#{ha["description"]}</span>")
          coordinates.unshift("\##{ha["name"]}")
          _line_strings << coordinates
        elsif ha["Polygon"]
          extrude = ha["Polygon"]["extrude"]
          altitudeMode = ha["Polygon"]["altitudeMode"]
          outer_coordinates = 
            ha["Polygon"]["outerBoundaryIs"]["LinearRing"]["coordinates"].split(/[,|\n|\t]/).map do |s|
              s.present? ?  s.to_f : nil
            end.compact
          outer_coordinates.unshift(altitudeMode)
          #outer_coordinates.unshift(extrude)
          outer_coordinates.unshift("<h5><strong>\##{ha["name"]}</strong></h5><span>#{ha["description"]}</span>")
          _polygons << outer_coordinates
        end
      end 

      @points = _points.to_json
      @line_strings = _line_strings.to_json
      @polygons = _polygons.compact.to_json
    end
  end

  private
  def site_params
    p = params.require(:site).permit(:team_id, :name, :address, :latitude, :longtitude, :memo, :kml, :kml_cache, :remove_kml, :tag_list, { label_ids: [] }, { comments_str: [] }, { comments: [] })
    p[:tag_list] = p[:tag_list].split(/[[:space:]]/).select {|li| li.length > 0}
    p[:label_ids] = p[:label_ids].select { |li| li.length > 0 }
    if p[:comments_str] && p[:comments_str].length > 0
      p[:comments] = p[:comments_str].map { |cs| Comment.new(content: cs, user_id: current_user.id) }
      p.delete(:comments_str)
    end
    return p
  end

  def set_site
    if !(@site = Site.find_by(id: params[:id]))
        flash[:alert]=I18n.t('views.messages.invalid_site_specified')
        redirect_to statics_top_path
    end 
  end

  def site_creator_or_team_owner?
    ((current_user.id == @site.user_id) || (current_user.id == @site.team.owner.id)) ? true : false
  end

  def belong?(_team_id)
    current_user.teams.pluck(:team_id).include?(_team_id) ? true : false
  end

  def check_specified_team
    if !(belong?(params[:team_id].to_i))
      flash[:alert]=I18n.t('views.messages.unauthorized_request')
      redirect_to statics_top_path
    end
  end

  def search_params
    sp = params.require(:q).permit!
    if sp[:tags_name_cont] && sp[:tags_name_cont].length > 0
      sp[:tags_name_cont_any] = sp[:tags_name_cont].split(/[[:space:]]/).select {|val| val.length > 0}
      sp.delete(:tags_name_cont)
    end
    return sp
  end

  def load_kml(_path)
    begin
      require "rexml/document"
      kml = REXML::Document.new(File.new(_path).read)
            
      if (elems_name=REXML::XPath.match(kml, '//Document/name')).length > 0
        @document_name = elems_name[0].text
      end
      if (elems_description=REXML::XPath.match(kml, '//Document/description')).length > 0
        @document_description = elems_description[0].text
      end

      if (elems_placemark = REXML::XPath.match(kml, '//Placemark')).length > 0
        hashes_placemark = elems_placemark.map { |elem| Hash.from_xml(elem.to_s) }  
        
        @tags_str=[]; @comments_str=[]
        hashes_placemark.each do |elem|
          ha = elem["Placemark"]
          mark = KmlPlaceMark.new(ha["name"], ha["description"], (ha.has_key?("Point") ? ha["Point"]["coordinates"] : nil))
          @tags_str << mark.to_tag
          @comments_str << mark.to_comment
        end
        return true
      else
        flash.now[:alert]=I18n.t('views.messages.no_placemark_in_kml')
        return false
      end
    rescue REXML::ParseException => ex
      flash.now[:alert]="#{I18n.t('views.messages.unexpected_file_format')}  (#{ex.message})"
      return false
    end
  end

  class KmlPlaceMark
    #attr_accessor :name, :description, :coorinates
    def initialize(_name, _description, _coordinates)
      @name = _name.strip if _name.present?
      @description = _description.strip if _description.present?
      @coordinates = _coordinates.strip if _coordinates.present?
    end

    def to_tag
      "##{@name}"
    end

    def to_comment
      "[\##{@name}]:#{@description}"
    end
  end

end

app/helpers/sites_helper.rb
module SitesHelper
  def choose_new_or_edit
    if action_name=="new" || action_name=="create" || action_name=="confirm"
      team_sites_path
    elsif action_name=="edit" || action_name=="update" || action_name=="confirm_edit"
      team_site_path
    end
  end

  def choose_method
     if action_name=="new" || action_name=="create" || action_name=="confirm"
       :post
     elsif action_name=="edit" || action_name=="update" || action_name=="confirm_edit"
       :patch
     end
   end
 
  def choose_new_or_edit_confirm
    if action_name == "new" || action_name == "create" || action_name == "confirm"
      confirm_team_sites_path
    elsif action_name == "edit" || action_name == "update" || action_name == "confirm_edit"
      confirm_edit_team_site_path
    end
  end
end

app/views/sites/_form.html.erb
<%= form_with(model: site,  url: choose_new_or_edit_confirm, method: :post, multipart: true, local: true) do |form| %>

<div class="container_article border border-dark">
    <h3>
      <i class="fa fa-info-circle" aria-hidden="true"></i></i>&nbsp;
      <%= I18n.t('views.labels.site_show_basic_attributes_block') %>
    </h3>

    <% if site.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(site.errors.count, "error") %> prohibited site from being saved:</h2>
        <ul>
        <% site.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <!-- 基本属性ブロック start -->
    <% if site.present? %>
      <input type="hidden" name="team_id" value="<%= site.team_id%>">
      <input type="hidden" name="id" value="<%= site.id %>">
    <% end %>
  
    <table>
    <tr>
      <td align="right"><%= form.label I18n.t('views.labels.site_name') %></td>
      <td><%= form.text_field :name, id: '', size: 48, class: "m-1 p-1" %></td>
    </tr>
    <tr>
      <td align="right"><%= form.label I18n.t('views.labels.site_address') %></td>
      <td><%= form.text_field :address, id: '', size: 48, class: "m-1 p-1" %></td>
    </tr>
    <tr>
      <td align="right"><%= form.label :labels, I18n.t('views.labels.filter_select_label') %></td>
      <td>
        <%= form.collection_check_boxes(:label_ids, Label.filter_team(current_user.keep_team_id), :id, :title) do |b| %>
          <%= b.label do %>
            <%= b.check_box %>
            <span class='badge badge-pill badge-light'>
              <%= b.text %>
            </span>
          <% end %>
        <% end %>
      </td>
    </tr>
    <tr>
      <td align="right"><%= form.label I18n.t('views.labels.site_memo') %></td>
      <td><%= form.text_field :memo, id: '', size: 48, class: "m-1 p-1" %></td>
    </tr>
    <tr>
      <td align="right"><%= form.label :tag_list, I18n.t('views.labels.site_hashtag') %></td>
      <td><%= form.text_field :tag_list, id: '', size: 48, class: "m-1 p-1" %></td>
    </tr>
    <tr>
      <td align="right">
        <%= form.label :kml, I18n.t('views.labels.site_kml') %><BR>
        <%#= button_tag raw("<i class=\"fas fa-2x fa-trash-alt\"></i>"), type: "reset", class: "btn btn-sm" %>
      </td>
      <td>
        <%= site.kml.path.split("/").last if site.kml.path %>        
        <%= form.file_field :kml, class: "p-1 btn-sm" %><BR>
        <%= form.check_box :remove_kml %><%= I18n.t('views.labels.site_remove_kml')%>        
        <%= form.hidden_field :kml_cache %>
      </td>
    </tr>    

    <tr><td>
        <%= form.submit I18n.t('views.labels.site_submit'), class: "btn btn-sm btn-success" %>
        </td>
    </tr>
    </table>
    <!-- 基本属性ブロック end -->

</div>
<% end %>

app/views/sites/index.html.erb
<article class="container_article">
  <h1><%= I18n.t('views.labels.site_index') %> @<%= current_user.keep_team.name %></h1>
 
  <!-- <h4><%#= I18n.t('views.labels.site_filter_cond') %></h4> -->
  <div class="site_index_search_condition border border-dark">
  
    <%= search_form_for(@q, url: team_sites_path(team_id: current_user.keep_team_id), id: 'filter_form', method: :get) do |form| %>
    <%#= search_form_for @q do |form| %>

      <table>

      <tr>
        <td align="right"><%= form.label :name_cont, I18n.t('views.labels.filter_input_name') %></td>
        <td>   
          <%= form.search_field :name_cont, id:'' %>
        </td>

        <td align="right"><%= form.label :address_cont, I18n.t('views.labels.filter_input_address') %></td>
        <td>   
          <%= form.search_field :address_cont, id:'' %>
        </td>
      </tr>

      <tr>
        <td align="right">
          <%= form.label :labels_id_in, I18n.t('views.labels.filter_select_label') %>
        </td>
        <td>          
          <%= form.collection_check_boxes(:labels_id_in, Label.filter_team(current_user.keep_team_id), :id, :title) do |b| %>
            <%= b.label do %>
              <%= b.check_box %>
              <span class='badge badge-pill badge-secondary'>
              <%= b.text %>	      
              </span>
            <% end %>
          <% end %>
        </td>
      </tr>

      <tr>
        <td align="right"><%= form.label :memo_cont, I18n.t('views.labels.filter_input_memo') %></td>
        <td>
          <%= form.search_field :memo_cont %>
        </td>
        <td align="right"><%= form.label :comments_content_cont, I18n.t('views.labels.filter_input_comment') %></td>
        <td><%= form.search_field :comments_content_cont %></td>
      </tr>


      <tr>
        <td align="right"><%= form.label :tags_name_cont, I18n.t('views.labels.filter_input_hashtag') %></td>
        <td>   
          <%= form.search_field :tags_name_cont, id:'' %>
        </td>
      </tr>
      <tr>
        <td align="right">
          <%= radio_button_tag :and_or, 0 %> And
          <%= radio_button_tag :and_or, 1 %> Or
        </td><td><BR></td><td><BR></td>
        <td align="right">
          <%= form.submit I18n.t('views.labels.site_filter'), class:"btn btn-sm btn-info" %>
          <button name="action" value="clear" type="button" class="clear-button btn btn-sm btn-warning"><%= I18n.t('views.labels.filter_clear') %></button> 
        </td>
      </tr>

    </table>
    <% end %>
  </div>

 <!-- <h4><%#= I18n.t('views.labels.site_index_index') %></h4> -->
  <div class="site_index_index">
    <div class="text-left">
      <%= link_to I18n.t('views.labels.link_site_new'), new_team_site_path(current_user.keep_team_id ) %>
    </div>
    <table class="table table-sm table-bordered table-resposive table-hover">
      <thead class="thead-dark">
      <!-- <thead class="thead-light"> -->
      <tr>
        <th><%= sort_link(@q, :id, I18n.t('views.labels.site_id'), {default_order: :desc}, {class: "site_index_sort_link"}) %></th>
        <th><%= sort_link(@q, :name, I18n.t('views.labels.site_name'), {default_order: :desc}, {class: "site_index_sort_link"}) %></th>
        <th><%= sort_link(@q, :address, I18n.t('views.labels.site_address'), {default_order: :desc}, {class: "site_index_sort_link"}) %></th>
        <th><%= I18n.t('views.labels.site_label') %></th>
        <th><%= sort_link(@q, :memo, I18n.t('views.labels.site_memo'), {default_order: :desc}, {class: "site_index_sort_link"}) %></th>
        <th><%= I18n.t('views.labels.site_hashtag') %></th>
<!--        <th><%#= sort_link(@q, :user_name, I18n.t('views.labels.site_username'), {default_order: :desc}, {class: "site_index_sort_link"}) %></th> -->
        <th><%= I18n.t('views.labels.site_username') %></th>
        <th><%= sort_link(@q, :created_at, I18n.t('views.labels.site_created_at'), {default_order: :desc}, {class: "site_index_sort_link"}) %></th>
        <th><%= sort_link(@q, :updated_at, I18n.t('views.labels.site_updated_at'), {default_order: :desc}, {class: "site_index_sort_link"}) %></th>
        <th></th><th></th>
      </tr>
    </thead>
    <tbody>


    <% @sites.each do |site| %>
      
      <tr>
        <td><%= link_to site.id, team_site_path(site.team.id, site.id), class: "btn btn-sm btn-primary" %></td>
        <td><%= site.name %></td>
        <td><%= site.address %></td>
        <td>
          <% site.site_labellings.each do |labelling| %>
            <span class="badge badge-pill badge-secondary mr-1 p-2"><%= labelling.label.title %></span><br>
          <% end %>
        </td>    
        <td><%= site.memo %></td>
        <td>
          <%= render 'sites/tag_list', tag_list: site.tag_list %>
        </td>
        <td><%= site.user.name %></td>
        <td><%= l site.created_at, format: :short %></td>
        <td><%= l site.updated_at, format: :short %></td>
        <td>
          <% if(current_user.keep_team.owner_id == current_user.id || site.user_id == current_user.id) %>
            <%= link_to I18n.t('views.labels.site_index_edit'), edit_team_site_path(site.team.id, site.id), class: "btn btn-sm btn-info", id: "link_edit_#{site.id}" %>
            <%#= link_to raw("<i class=\"fa fa-pencil-square-o  fa-2x\" aria-hidden=\"true\"></i>"), edit_team_site_path(site.team.id, site.id), class: "btn-outline-info", id: "link_edit_#{site.id}" %>

          <% end %>
        </td>
        <td>
          <% if(current_user.keep_team.owner_id == current_user.id || site.user_id == current_user.id) %>
            <%= link_to I18n.t('views.labels.site_index_delete'), team_site_path(site.team.id, site.id), method: :delete,  data: { confirm: I18n.t('views.messages.really_want_to_delete') }, class: "btn btn-sm btn-danger", id: "link_delete_#{site.id}" %>
            <%#= link_to raw("<i class=\"fa fa-trash fa-2x\" aria-hidden=\"true\"></i>"), team_site_path(site.team.id, site.id), method: :delete,  data: { confirm: I18n.t('views.messages.really_want_to_delete') }, class: "btn-outline-danger", id: "link_delete_#{site.id}" %>
          <% end %>
        </td>
      </tr>

      <% end %>

    </tbody>
    </table>
    <%= paginate @sites, theme: 'twitter-bootstrap-4'%>
  </div>
</article>

app/views/sites/show.html.erb
<article class="container_article">
  <h1><%= I18n.t('views.labels.site_show') %></h1>  

  <div class="container-fluid">

    <h4 class="font-weight-bold">
      <i class="fa fa-info-circle" aria-hidden="true"></i>
      <%= I18n.t('views.labels.site_show_basic_attributes_block') %>
    </h4>
    <!-- 基本属性ブロック start -->
    <a name="basics"></a>
    <section class="site_show_basic_block border border-info">
      <table>
        <tr>
          <td align="right"><div class="font-weight-bold"><%= I18n.t('views.labels.site_id') %>：&nbsp;</div></td>
          <td><div class="site_show_basic_item"><%= @site.id %></div></td>
        </tr>

        <tr>
          <td align="right"><div class="font-weight-bold"><%= I18n.t('views.labels.site_url') %>：&nbsp;</div></td>
          <td>
            <div class="site_show_basic_item">
              <div id="request_url">
                <%= request.url %>&nbsp;&nbsp;
                <a href="javascript:void(0)" onclick="site_link_copy()"><i class="fa fa-clipboard fa-lg" aria-hidden="true"></i></a>
              </div>
            </div>
          </td>
        </tr>

        <tr>
          <td align="right"><div class="font-weight-bold"><%= I18n.t('views.labels.site_name') %>：&nbsp;</div></td>
          <td><div class="site_show_basic_item"><%= @site.name %></div></td>
        </tr>

        <tr>
          <td align="right"><div class="font-weight-bold"><%= I18n.t('views.labels.site_address') %>：&nbsp;</div></td>
          <td><div class="site_show_basic_item"><%= @site.address %></div></td>
        </tr>

        <tr>
          <td align="right"><div class="font-weight-bold"><%= I18n.t('views.labels.site_label') %>：&nbsp;</div></td>
          <td>
          <div class="site_show_basic_item">
            <% @site.site_labellings.each do |labelling| %>
              <span class="badge badge-pill badge-secondary mr-1 p-2"><%= labelling.label.title %></span>&nbsp;
            <% end %>          
          </div>
          </td>
        </tr>

        <tr>
          <td align="right"><div class="font-weight-bold"><%= I18n.t('views.labels.site_memo') %>：&nbsp;</div></td>
          <td><div class="site_show_basic_item"><%= @site.memo %></div></td>
        </tr>

        <tr>
          <td align="right"><div class="font-weight-bold"><%= I18n.t('views.labels.site_hashtag') %>：&nbsp;</div></td>
          <td>
            <div class="site_show_basic_item text-monospace">
              <% @site.tag_list.each do |tag| %>
                <strong><%= tag %></strong>
              <% end %>
            </div>
          </td>
        </tr>
      </table>
    </section>
    <!-- 基本属性ブロック end -->

    <!-- mapブロック start -->
    <h4 class="font-weight-bold">
      <i class="fa fa-map-marker" aria-hidden="true"></i>
      <%= I18n.t('views.labels.site_show_map_block') %>
    </h4>
    <a name="maps"></a>
    <section class="site_show_map_block">  
      <div class="row">

        <% if @site.kml.present? %>
          <div class="col-auto">
            <span class="text-monospace"><%= I18n.t('views.labels.site_kml') %></span><BR>
            <div id="mapDiv" style="width:600px; height:300px;"></div>
            <input name="tid" type="hidden" value="<%= @site.team_id %>" class="col-auto__hidden__tid">
            <input name="arr_json_points" type="hidden" value="<%= @points %>" class="arr_json_points">
            <input name="arr_json_lines" type="hidden" value="<%= @line_strings %>" class="arr_json_lines">
            <input name="arr_json_polygons" type="hidden" value="<%= @polygons %>" class="arr_json_polygons">
          </div>
        <% end %>
        <% if @site.address.present? %>
          <div class="col-auto">
            <span class="text-monospace"><%= I18n.t('views.labels.site_address') %></span><BR>
            <iframe frameborder="0" 
                      style="border:0; width: 600px; height: 300px" 
                      src="https://maps.google.co.jp/maps?output=embed&q=<%= @site.address%>">
            </iframe>
          </div>
        <% end %>

      </div>
  
      <div>
      	<ul id="site_show_clickmenu">
		      <li>
            <div id="li_show_waitingpoints_u1">
              <i class="fas fa-map-marker-alt"></i>&nbsp;<%= I18n.t('views.labels.site_show_clickmenu1') %>
			      </div>
		      </li>
		      <li>
            <div id="li_show_waitingpoints_u5">
              <i class="fas fa-map-marker"></i>&nbsp;<%= I18n.t('views.labels.site_show_clickmenu2') %>
			      </div>
		      </li>
		      <li>
            <div id="li_add_waitingpoint">
              <i class="fa fa-location-arrow"></i>&nbsp;<%= I18n.t('views.labels.site_show_clickmenu3') %>
      			</div>
          </li>
    	  </ul>
      </div> 

      <div id="input_add_waitingpoint" title="<%= I18n.t('views.labels.site_show_clickmenu3_dialog') %>">
        <table>
          <tr>
            <th>名前</th>
            <td><input type="text" id="inputName" size="36" maxlength="256"></td>
          </tr>   
          <tr>
            <th>メモ</th>
            <td><input type="text" id="inputMemo" size="36" maxlength="1024" /></td>
          </tr>
        </table>
      </div>   
    
    </section>
    <!-- mapブロック end -->

    <!-- コメントブロック start -->
    <h4 class="font-weight-bold">
   <!--   <i class="fa fa-hand-o-right" aria-hidden="true"></i> -->
      <i class="fa fa-commenting-o" aria-hidden="true"></i>
      <%= I18n.t('views.labels.site_show_comments_block') %>
    </h4>
    <a name="comments"></a>
    <section class="site_show_comment_block border border-info">

      <div id="comments_area">
        <!-- コメント一覧 -->
        <%= render partial: 'comments/index', locals: { comments: @comments, site: @site } %>
      </div>
    
      <!-- コメント入力欄 -->
      <%= render partial: 'comments/form', locals: { comment: @comment, site: @site } if @comments.length < POSTMAXSIZE::COMMENT %>

    </section>
    <!-- コメントブロック end -->

    <!-- 画像ブロック start -->
    <h4 class="font-weight-bold">
      <i class="fa fa-picture-o" aria-hidden="true"></i>
      <%= I18n.t('views.labels.site_show_images_block') %>
    </h4>
    <a name="images"></a>
    <section class="site_show_image_block">
      <div class="row">
        <% @image_posts.each do |post| %>
          <div class="col-auto">
            <div class="site_show_menu_on_image m-1 p-1">
              <%= link_to post.image_url, "data-lightbox": post.image_url do %>
                <%= image_tag(post.image_url, class:"site_show_image", alt: "#{File.basename(post.image.path, '.*')}" ) %>
              <% end %>
              <% if (current_user.id == post.user_id) || (current_user.id == current_user.keep_team.owner_id) %>
                <div class="site_show_menu">
                  <%= link_to '×', image_post_path(id: post.id), method: :delete, data: {confirm: I18n.t('views.messages.really_want_to_delete') } %>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>      

      <div class="row">
        <div class="col-auto">
          <%= link_to I18n.t('views.labels.link_add_image'), new_team_site_image_post_path(@site.team.id, @site.id) if @image_posts.length < POSTMAXSIZE::IMAGEPOST%>
        </div>
        <div class="col-auto">
          <%= link_to I18n.t('views.labels.link_back_to_site_index'), team_sites_path %>  
        </div>
      </div>                  
    
    </section>
    <!-- 画像ブロック end -->                      
    
  </div>
  <!-- .container_fluid -->
  <!-- 全体コンテナ end -->                

</article>